version: '3'

services:
  backend:
    env_file:
        "./.env"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "sisi-be"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "sisi-fe"
    ports:
      - "3000:3000"
    links:
      - "backend:be"